### PR TITLE
remove all

### PR DESCRIPTION
**Pull request by hakjong**

### CODE REVIEW

**Comment by mell03** [comment]
It seems promising.

**Comment by hakjong** [comment]
good

**Comment by mell03** [comment]
> good

Not good, perfect

**Comment by hakjong** [comment]
su set

**Comment by Okies** [comment]
jalanala meolimeoli

**Comment by mell03** [comment]
> jalanala meolimeoli

I can not figure out meaning of this comment. 

Could you explain about it in detail?

**Comment by Okies** [comment]
> > jalanala meolimeoli
> 
> I can not figure out meaning of this comment.
> 
> Could you explain about it in detail?

Growing head man

**Comment by hakjong** [comment]
hi

**Comment by hakjong** [comment]
we can make comments though the request is closed!!!

**Comment by mell03** [comment]
> we can make comments though the request is closed!!!

Thank you for a great information.

**Pull request closed without merging**
